### ISSUE TITLE
Not working with Xcode 9.3

### ISSUE THREAD

**Issue by chr0n1cle** [karek314/HandyIPAPatcher#1]
using extract_thin.sh, give this error:

fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: tmp/Payload/app.ipa.app/app.ipa (No such file or directory)

**Comment by karek314** [comment]
Hi,

That was my unclear design resulting in confusing usage rather lipo issue. I'ven't explained this correctly, previously "AppName" as launch parameter was exact binary name in Payload directory. I believe that's why it didn't worked for you, maybe renaming ipa to app.ipa was confusing as well.

Here is improved version.
https://github.com/karek314/HandyIPAPatcher/commit/0b615ec84cdef107ba5fed540edd373cadc6b30d

In main repository you will find fixed readme. Basically, download this repository, drag IPA file there and run scripts.

In most cases
`bash extract_thin.sh`
work with files and repack
`bash replace_bin.sh fat trim`

I will leave it open for few days until you confirm it works fine for you.

**Comment by chr0n1cle** [comment]
it works fine, thanks
